{% set conda_name = "pyemma" %}
{% set name = "pyEMMA" %}
{% set version = "2.5.7" %}
{% set sha256 = "82a3b09a48e4b51ef4cc0634b163f3e5856fc94c32b6b1f78f6c1f421da292df" %}

package:
  name: {{ conda_name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 4
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  skip: True  # [py27 or python_impl == "pypy"]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}

  host:
    - cython
    - intel-openmp  # [osx]
    - llvm-openmp  # [osx]
    - mdtraj
    - numpy
    - python
    - pip
    - scipy
    - setuptools
    - pybind11

  run:
    - bhmm >=0.6.3,<0.7
    - decorator >=4.0.0
    - h5py
    # TODO: there is a dead-lock, when blosc is enabled during hdf5 pickling!
    #- blosc-hdf5-plugin  # [not win]
    - intel-openmp  # [osx]
    - matplotlib-base
    - mdtraj >=1.9.2
    - msmtools >=1.2
    - {{ pin_compatible('numpy') }}
    - pathos
    - psutil >=3.1.1
    - python
    - pyyaml
    - scipy
    - setuptools
    - tqdm >=4.36.1

test:
  imports:
    - pyemma

about:
  home: http://github.com/markovmodel/pyemma
  license: LGPL-3.0-or-later
  license_file: LICENSE.txt
  summary: "PyEMMA (EMMA = Emma's Markov Model Algorithms) is an open source Python/C package for analysis of extensive molecular dynamics simulations"

  description: |
    PyEMMA (EMMA = Emma's Markov Model Algorithms) is an open source Python/C package
    for analysis of extensive molecular dynamics simulations.
    In particular, it includes algorithms for estimation, validation and analysis of:
      * Clustering and Featurization
      * Markov state models (MSMs)
      * Hidden Markov models (HMMs)
      * Multi-ensemble Markov models (MEMMs)
      * Time-lagged independent component analysis (TICA)
      * Transition Path Theory (TPT)
  doc_url: http://emma-project.org
  dev_url: https://github.com/markovmodel/pyemma

extra:
  recipe-maintainers:
    - franknoe
    - marscher
    - clonker
