{% set conda_name = "pyemma" %}
{% set name = "pyEMMA" %}
{% set version = "2.5.5" %}
{% set sha256 = "dfadd3f4d3d5019d49175eaa31160b07f17bdafe91180ddc916d25c83b757308" %}

package:
  name: {{ conda_name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - build_flags.patch

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"
  # skip this, because we would need to built extension with vc14, but ci is configured to use vc9 for py27
  skip: True  # [win and py27]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - cython
    - intel-openmp  # [osx]
    - llvm-openmp  # [osx]
    - mdtraj
    - numpy
    - python
    - pip
    - scipy
    - setuptools

  run:
    - bhmm >=0.6.3,<0.7
    - decorator >=4.0.0
    - h5py
    - intel-openmp  # [osx]
    - matplotlib
    - mdtraj >=1.8
    - mock # TODO: remove when py3k only.
    - msmtools >=1.2
    - {{ pin_compatible('numpy') }}
    - pathos
    - psutil >=3.1.1
    - python
    - pyyaml
    - scipy
    - setuptools
    - six >=1.10
    - thermotools >=0.2.6
    - tqdm >=4.23

test:
  imports:
    - pyemma

about:
  home: http://github.com/markovmodel/pyemma
  license: LGPLv3+
  license_file: LICENSE.txt
  summary: "PyEMMA (EMMA = Emma's Markov Model Algorithms) is an open source Python/C package for analysis of extensive molecular dynamics simulations"

  description: |
    PyEMMA (EMMA = Emma's Markov Model Algorithms) is an open source Python/C package
    for analysis of extensive molecular dynamics simulations.
    In particular, it includes algorithms for estimation, validation and analysis of:
      * Clustering and Featurization
      * Markov state models (MSMs)
      * Hidden Markov models (HMMs)
      * Multi-ensemble Markov models (MEMMs)
      * Time-lagged independent component analysis (TICA)
      * Transition Path Theory (TPT)
  doc_url: http://emma-project.org
  dev_url: https://github.com/markovmodel/pyemma

extra:
  recipe-maintainers:
    - franknoe
    - marscher
