{% set conda_name = "pyemma" %}
{% set name = "pyEMMA" %} 
{% set version = "2.3" %}
{% set sha256 = "f7ea0885a00960d5dbfb34b9b29ae977fb134405e6f3196fce2493731d0bbb19" %}

package:
  name: {{ conda_name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python -B setup.py install --single-version-externally-managed --record record.txt

requirements:
  build:
    - cython >=0.20
    - mdtraj >=1.8
    - numpy x.x
    - python
    - setuptools
  run:
    - bhmm >=0.6,<0.7
    - decorator >=4.0.0
    - funcsigs
    - joblib >0.8.4
    - matplotlib
    - mdtraj >=1.8
    - mock
    - msmtools >=1.1.4
    - numpy x.x
    - progress_reporter >=1.3.1
    - psutil >=3.1.1
    - python
    - pyyaml
    - scipy
    - setuptools
    - six >=1.1.0
    - thermotools >=0.2.4

test:
  imports:
    - pyemma

about:
  home: http://github.com/markovmodel/pyemma
  license: LGPLv3+ 
  license_file: LICENSE.txt
  summary: 'PyEMMA (EMMA = Emma’s Markov Model Algorithms) is an open source Python/C package for analysis of extensive molecular dynamics simulations'

  description: |
    PyEMMA (EMMA = Emma’s Markov Model Algorithms) is an open source Python/C package
    for analysis of extensive molecular dynamics simulations.
    In particular, it includes algorithms for estimation, validation and analysis of:
      * Clustering and Featurization
      * Markov state models (MSMs)
      * Hidden Markov models (HMMs)
      * Multi-ensemble Markov models (MEMMs)
      * Time-lagged independent component analysis (TICA)
      * Transition Path Theory (TPT)
  doc_url: http://emma-project.org
  dev_url: https://github.com/markovmodel/pyemma

extra:
  recipe-maintainers:
    - franknoe
    - marscher
