package:
  name: pyemma-dev
  # version number: [base tag]+[commits-upstream]_[git_hash]
  # eg. 2.0+0_g8824162
  version: "0" 

source:
  git_url: https://github.com/marscher/pyemma
  git_rev: packaging

build:
  script_env:
   - CIRCLE_TEST_REPORTS
   - OMP_NUM_THREADS
   - PYEMMA_NJOBS
  script: python setup.py install --single-version-externally-managed --record record.txt
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - llvm-openmp # [osx]
    - intel-openmp # [osx]

  host:
    - cython
    - intel-openmp # [osx]
    - mdtraj
    # actually we could build with np18, but fastcluster (dep of mdtraj, we link against) is only avail for 1.9
    - numpy 1.9.*  # [not (win and (py35 or py36))]
    - numpy 1.9.*  # [win and py35]
    - numpy 1.11.*  # [win and py36]
    - python
    - scipy
    - setuptools

    #- toolchain, can not use because of:
    #gcc: error: unrecognized command line option ‘-fstack-protector-strong’
    #gcc: error: unrecognized command line option ‘-fno-plt’

  run:
    - bhmm >=0.6.3,<0.7
    - decorator >=4.0.0
    - h5py
    - intel-openmp # [osx]
    - matplotlib
    - mdtraj >=1.8
    - mock # TODO: remove when py3k only.
    - msmtools >=1.2
    - numpy >=1.9  # [not (win and (py35 or py36))]
    - numpy >=1.9  # [win and py35]
    - numpy >=1.11 # [win and py36]
    - pathos
    - psutil >3.1
    - python
    - pyyaml
    - scipy
    - setuptools
    - six >=1.10
    - thermotools >=0.2.6
    - tqdm >=4.23

test:
  source_files:
    - conftest.py
    - setup.cfg
  files:
    - matplotlibrc
  requires:
    - pytest
    - pytest-cov
    - coverage
   # TODO: disabled on win64, until https://bugs.python.org/issue31701 is fixed.
    - pytest-faulthandler # [not win]
    - pytest-xdist
    - scikit-learn
    # https://github.com/Frozenball/pytest-sugar/issues/124
    #- pytest-sugar

about:
  home: http://emma-project.org
  license: GNU Lesser Public v3+
  summary: "EMMA: Emma's Markov Model Algorithms"

extra:
  recipe-maintainers:
   - marscher
